### ISSUE TITLE
What is process to run tests?

### ISSUE THREAD

**Issue by wakemaster39** [flowerysong/ansible-sensu-go#2]
How does one go about running these tests?

It looks like it is pytest against your local machine? I have never built a plugin before so can this somehow utilize molecule so tests can be run in CI and on a clean slate?

Assets cannot be deleted which makes having a clean slate required for the PR and tests I supplied.

**Comment by flowerysong** [comment]
At the moment you have to be me to run the tests as written.

This collection is alpha quality (I'm a little surprised you found it) and, as the README notes, relies on a forked version of Ansible for `module_defaults` handling. Each playbook gets [an ephemeral instance of Sensu Go](https://github.com/flowerysong/ansible-sensu-go/blob/f97cfca/test/conftest.py#L22-L37) (though that probably needs more fiddling to work reliably), which is then used for all tasks within that playbook (xref https://github.com/flowerysong/ansible-sensu-go/blob/f97cfca/test/test_sensu_go_check.yml#L5-L7). With vanilla Ansible this `module_defaults` setting is completely ignored, so tests will incorrectly run against port 8080 on localhost.

**Comment by wakemaster39** [comment]
The power of google and the determination to no write this myself is a powerful thing lol. As I continue down testing these out and making sure it does what I need I'll keep pushing back changes I find. For an alpha quality, it is pretty slick the way you wrapped up idempotency.

I have avoided the use of module_defaults for now in testing, and it looks like I can for now just use the `password` and `username` line in every entry until 2.9 comes out to avoid the default problem. You could can do the same with the tests and url as I spent far too long debugging the fact I was overriding URL when I was attempting to get the asset_info working.

**Comment by flowerysong** [comment]
6e46e4304eed26c961c2e427d3fcac4a052ca5c1 removes the reliance on `module_defaults` in tests, so they should work as intended without too much fiddling now.

**Comment by flowerysong** [comment]
Sorry for making this such a moving target, but collections are still very new so the cutting edge is very sharp.

The pytest framework was a stop-gap so that I could do testing while waiting for the upstream tools to catch up; the tool used within Ansible for module testing now has preliminary support for testing collections, so I've ported the integration tests to that framework. This has a number of benefits, including better display of what's happening during tests (`ansible-test integration -vvv`) and an easy way to run specific tests instead of the whole suite (e.g. `ansible-test integration sensu_go_asset`).

The main difference in the tests themselves is that I'm using YAML anchors to set the connection information on tasks; I avoided it originally because it's slightly ugly, but it works and doesn't require any patches to Ansible. [The initial set_fact](https://github.com/flowerysong/ansible-sensu-go/blob/eb1f042c/test/integration/targets/sensu_go_asset/tasks/main.yml#L4-L7) doesn't actually accomplish anything during the playbook run, but it provides a YAML anchor that the rest of the file [can reference](https://github.com/flowerysong/ansible-sensu-go/blob/eb1f042c/test/integration/targets/sensu_go_asset/tasks/main.yml#L27) and avoid excessive repetition.

So, to address the original question, this is how you run tests:
```
git clone https://github.com/ansible/ansible
git clone https://github.com/flowerysong/ansible-sensu-go collections/ansible_collections/flowerysong/sensu_go
virtualenv venv
. venv/bin/activate
pip install ansible pycodestyle
. ansible/hacking/env-setup
cd collections/ansible_collections/flowerysong/sensu_go
ansible-test integration
ansible-test sanity --test pep8
```

There are other sanity tests, but many of them don't yet work and some of them I don't care about.
